---
- name: Setting up a WEBserver for work
  hosts: WEB_SERVERS
  become: yes

  vars:
   source_file1: ../public_server/html/index1.html
   source_folder1: ../public_server/
   destin_file1: /var/www/html/index.html
   destin_folder1: /var/www/html/

  tasks:
   - name: updating repositories
     shell: yum -y update
     
   - name: install apache web-server
     yum: name=httpd state=latest

   - name: start apache
     service: name=httpd state=started enabled=yes

   - name: copy internet page
     copy: src={{ source_file1 }} dest={{ destin_file1 }} mode=0555
     notify: Restart apache

   - name: copy public web files
     copy: src={{ item }} dest={{ destin_folder1 }} mode=0555
     with_fileglob: "{{ source_folder1 }}/*.*"

  handlers:
   - name: Restart apache
     service: name=httpd state=restarted
